### PR TITLE
Scenario 4 Frame Animation of Capetown Table Mountain Images

### PR DESCRIPTION
**Pull request by mthulisi-zimba**

### CODE REVIEW

**Comment by LadySith** [comment]
@mthulisi-zimba your animation should be in a separate activity, not the MainActivity. I'm looking at your code and I see you have included animation code in the Main Activity. You should only add a button to the main activity that sends us to the activity with your animation. Don't add animations to the main activity.

**Comment by mthulisi-zimba** [comment]
@LadySith 
Hie

My animation is in a seperate activity called TableMountain Activity and the only lines I added to the main activity are 

fun startScenario4(view: View){
        val intent = Intent(this,TableMountainActivity::class.java)
        startActivity(intent)
    }

The rest of the code inside the main is not mine.

**Comment by mthulisi-zimba** [comment]
@LadySith 

This code is not mine. It was merged yesterday

 public void fade (view: View) {
        
        ImageView capeTownImage = findViewById(R.id.capetown)
        ImageView okavangoImage = findViewById(R.id.okavango)
        
        if(capetownShowing) {
            
             boolean capetownShowing = false
            
            capeTownImage.animate().alpha(0).setDuration(1000)
            okavangoImage.animate().alpha(1).setDuration(1000)
        }
        else {
            
            boolean capetownShowing = true
            
            capeTownImage.animate().alpha(1).setDuration(1000)
            okavangoImage.animate().alpha(0).setDuration(1000)
        }

**Comment by LadySith** [comment]
Ah okay. I see. I'll fix this before the merge then

**Pull request merged**
